[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = "Bookstore API"
authors = ["Helbert guirra <helbert.guirra@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^9.0.2"
factory-boy = "^3.3.3"
django = "^4.2"
djangorestframework = "^3.14"
django-extensions = "^4.1"
django-debug-toolbar = "^4.3"
psycopg2-binary = "^2.9.11"
pytest-django = "^4.12.0"
gitpython = "^3.1.46"
whitenoise = "^6.12.0"
gunicorn = "^25.3.0"
dj-database-url = "^3.1.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
mypy = "^1.19.1"
faker = "^40.11.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"